<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="iTextSharp" Version="5.5.13.3" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="12.0.0" />
    <PackageReference Include="PasswordGenerator" Version="2.1.0" />
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThoughtFocus.Common.Utilities\ThoughtFocus.Common.Utilities.csproj" />
    <ProjectReference Include="..\ThoughtFocus.DocumentManager\ThoughtFocus.DocumentManager.csproj" />
    <ProjectReference Include="..\ThoughtFocus.Domain\ThoughtFocus.Domain.csproj" />
    <ProjectReference Include="..\ThoughtFocus.Repository\ThoughtFocus.Repository.csproj" />
  </ItemGroup>

</Project>
