<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThoughtFocus.Domain\ThoughtFocus.Domain.csproj" />
    <ProjectReference Include="..\ThoughtFocus.Repository\ThoughtFocus.Repository.csproj" />
  </ItemGroup>

</Project>
