# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
  - develop
 
pool:
  name: Azure Pipelines
  vmImage: windows-latest
  demands:
    - msbuild
    - visualstudio
    - vstest
 
stages:
  - stage: CI
    jobs:
    - job: CIWork
      steps:
      - task: NuGetToolInstaller@1
        inputs:
          versionSpec: '6.1.0'
        displayName: 'Install Nuget'
      - task: NuGetCommand@2
        inputs:
            command: 'restore'
            restoreSolution: '**/*.sln'
            feedsToUse: 'select'
            displayName: 'Restore Nuget'
      - task: VSBuild@1
        inputs:
          solution: '**\*.sln'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
          platform: 'any cpu'
          configuration: 'release'
        displayName: 'Build Solution'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
        displayName: 'Publish Artifacts'